# Generated by Django 4.1.7 on 2023-03-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tag_post_tagss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
