# Generated by Django 4.1.7 on 2023-03-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tagss',
            new_name='tags',
        ),
    ]
